version: "3"
services:
    application:
        build: .
        restart: always
        ports:
            - 8080:8080
        container_name: {{container_name}}
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://{{URL:PORT}}/cliff?useSSL=false&allowPublicKeyRetrieval=true
            SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
            SPRING_DATASOURCE_USERNAME: {{USERNAME}}
            SPRING_DATASOURCE_PASSWORD: {{PASSWORD}}
        networks:
            - {{network_name}}

networks:
    {{network_name}}:
